### ISSUE TITLE
Update branches not deleted when PR merged

### ISSUE THREAD

**Issue by jglick** [jenkins-x/updatebot#68]
Not sure if this is a Prow (Tide?) issue or updatebot, but filing here for triage.

Take https://github.com/jenkins-x/jenkins-x-serverless/pull/55 for example. The bot created a branch https://github.com/jenkins-x/jenkins-x-serverless/tree/updatebot-f78b8069-9a60-462e-871a-486764a825e0 and filed a PR from it; then the PR was merged by something (again, Prow? the bot?); but this branch was left in the origin repository. So when I `git pull` I get

```
…lots of output…
 * [new branch]      updatebot-c6ac0fcb-6214-4c30-bc9f-37787cfa2ea1 -> origin/updatebot-c6ac0fcb-6214-4c30-bc9f-37787cfa2ea1
 * [new branch]      updatebot-dbc4aa12-def5-4c62-b376-acb8cf3ca3ff -> origin/updatebot-dbc4aa12-def5-4c62-b376-acb8cf3ca3ff
 * [new branch]      updatebot-f78b8069-9a60-462e-871a-486764a825e0 -> origin/updatebot-f78b8069-9a60-462e-871a-486764a825e0
Updating 8fb5380..f414f50
Fast-forward
…
```

These origin refs are now trash and need to be collected.

**Comment by jglick** [comment]
Based on [this](https://github.com/kubernetes/test-infra/blob/4da5c1c747c9c219e117824cbeade7d0c763c1d9/prow/tide/tide.go#L784-L832) and [this](https://github.com/kubernetes/test-infra/blob/4da5c1c747c9c219e117824cbeade7d0c763c1d9/prow/github/client.go#L1996-L2017) it seems to be missing functionality in Tide, though that leaves open the question of where it _should_ be. I am presuming that the normal upstream usage of Tide is to merge PRs filed by actual humans, generally in a fork, who might take umbrage at their branch being deleted without warning. (Sometimes people merging _my_ PRs delete my fork branch; sometimes they leave it, and I delete it when I get the notification.) At any rate, the usage from updatebot is a bit special in that it created the branch to begin with, so it should be responsible for deleting it too.

**Comment by jglick** [comment]
I see [this code](https://github.com/jenkins-x/updatebot/blob/a08fdec38654a96f8bc5785b59b086193e861911/updatebot-core/src/main/java/io/jenkins/updatebot/commands/UpdatePullRequests.java#L170-L172) suggesting that [by default](https://github.com/jenkins-x/updatebot/blob/a08fdec38654a96f8bc5785b59b086193e861911/updatebot-core/src/main/java/io/jenkins/updatebot/commands/UpdatePullRequests.java#L65-L66) it was _intended_ to do this. But maybe that predated Prow?

**Comment by ryandawsonuk** [comment]
Yeah delete branch feature was based on updatebot itself merging the branches and did indeed predate prow.

**Comment by jglick** [comment]
Maybe https://github.com/kubernetes/test-infra/issues/10398?

**Comment by jglick** [comment]
As of https://github.com/kubernetes/test-infra/pull/10443 I think it should suffice to set up the `branchcleaner` plugin when installing in `--prow` mode.
